# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('FETraining', '0003_auto_20170511_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BinaryField(default=True),
        ),
        migrations.AlterModelTable(
            name='name',
            table='Name',
        ),
    ]
