# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('FETraining', '0004_auto_20170511_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='FETraining.models',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='Publisher',
        ),
    ]
