# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('FETraining', '0005_auto_20170511_1411'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
