# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('FETraining', '0007_auto_20170512_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='salutation',
            field=models.CharField(blank=True,
                                   choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'),
                                            ('Dr', 'Dr'), ('Prof', 'Prof')],
                                   max_length=10),
        ),
    ]
